[package]
name = "backtrace-rust"
version = "0.1.0"
authors = ["laurentiustefan97 <steflaurentiu@gmail.com>"]
edition = "2018"

[features]
logging = []

[dependencies]
gimli = "0.21"
object = "0.17"
memmap = "0.7"
addr2line = "0.12"
rustc-demangle = "0.1"
